[OS-2728] adding logger via middleware - camunda library v1.0.0
blacklane/go-libs pull request #100
Opened 2022-01-26 07:14 UTC by shruthiMaganahalli

this is PR adds context to task handler of camunda module

this PR is one of the two PRs of this ticket

purpose of adding context is to inject logger using Middlewear.
In future we can extend it to adding tracking number, etc.

As this a major change which is not backward compatible, we are changing the version number of the library

2022-01-26 15:27 UTC, shane-blacklane approved these changes

2022-01-27 09:40 UTC, sabaraouf approved these changes

2022-01-28 09:49 UTC, giulliano-bueno requested changes
Please check your commit message. It has to comply with our [policy](https://github.com/blacklane/go-libs#commit-messages-issues-and-pull-requests), please.

2022-01-31 12:55 UTC, D-side-BL approved these changes

2022-01-31 14:16 UTC, merged

2022-01-31 14:17 UTC, D-side-BL commented
There seem to be no [code owners](https://github.com/blacklane/go-libs/blob/master/CODEOWNERS) active at this time (@giulliano-bueno is out this week, Anderson's gone), so I took the liberty to admin-merge this. Blame me if it blows up 🙂