logger: adding body to http logger
blacklane/go-libs pull request #110
Opened 2022-03-16 10:54 UTC by joserojasbl

[Ticket](https://blacklane.atlassian.net/browse/CHAR-3182?atlOrigin=eyJpIjoiNjViYTNjYmI5MzlkNGUzYTgzZmE2OTlhNTIwYWJiZWYiLCJwIjoiaiJ9)

2022-03-17 08:37 UTC, mariasoul-blacklane approved these changes

2022-03-24 13:05 UTC, giulliano-bueno requested changes
Good work! I changed the PR title to reflect the standard used by this public repository tho and left some comments.

2022-03-24 13:08 UTC, giulliano-bueno commented on logger/middleware/http.go
> +		_ = json.Unmarshal(body, &b)
[suggestion]
Reconsider ignoring the error returned by `Unmarshal` and handle the error properly.

2022-03-24 13:12 UTC, giulliano-bueno commented on logger/middleware/http_test.go
> +	want := `{"level":"info","application":"TestHTTPRequestLogger","host":"example.com","ip":"localhost","params":"","path":"/do_not_skip","request_id":"","tracking_id":"","user_agent":"","verb":"GET","
[question]
How useful is it to expect `body: null`?

2022-03-24 13:23 UTC, joserojasbl commented on logger/middleware/http.go
> +		_ = json.Unmarshal(body, &b)
Fixing this. (In my head it was already fixed)

2022-03-24 13:25 UTC, joserojasbl commented on logger/middleware/http_test.go
> +	want := `{"level":"info","application":"TestHTTPRequestLogger","host":"example.com","ip":"localhost","params":"","path":"/do_not_skip","request_id":"","tracking_id":"","user_agent":"","verb":"GET","
Request with params doesn't have a body, and the opposite is true also (POST with Body, params==nil)

2022-03-24 13:33 UTC, joserojasbl commented on logger/middleware/http.go
> +func filterBody(body []byte, filterKeys interface{}) map[string]interface{} {
The Keys are coming from the context so that's why is an Interface{}, but I'm going to add the Casting to `[]string `before calling this method.

2022-04-04 08:57 UTC, giulliano-bueno approved these changes

2022-04-05 07:48 UTC, mariasoul-blacklane approved these changes
Great stuff :100: Just a question!

2022-04-05 07:48 UTC, mariasoul-blacklane commented on logger/internal/constants.go
> +var DefaultKeys = []string{"new_payer_email", "new_booker_email", "email", "new_booker_mobile_phone",
Just a question, why do we leave default values in the library?

2022-04-11 09:29 UTC, merged