[MID-78] feat: support otlp http trace exporter
blacklane/go-libs pull request #124
Opened 2022-05-26 14:12 UTC by jcyamacho

2022-05-27 06:35 UTC, shane-blacklane approved these changes
:clap: :rocket:

2022-05-27 16:45 UTC, IvanMartinezBL requested changes

2022-05-27 16:45 UTC, IvanMartinezBL commented on RELEASING.md
> +First, decide which module sets will have their versions chagned and what those
```suggestion
First, decide which module sets will have their versions changed and what those
```

2022-05-27 16:45 UTC, IvanMartinezBL commented on RELEASING.md
> +include the curated chagnes your included in the changelog in the description.
```suggestion
include the curated changes you included in the changelog in the description.
```

2022-05-27 16:45 UTC, IvanMartinezBL commented on RELEASING.md
> +Finally create a Release on GitHub. If you are release multiple versions for
```suggestion
Finally create a Release on GitHub. If you are releasing multiple versions for
```

2022-05-27 16:45 UTC, IvanMartinezBL commented on versions.yaml
> +  - github.com/blacklane/go-libs/x/events/examples/without-auth
```suggestion
  - github.com/blacklane/go-libs/x/events/examples/without-auth

```

2022-05-27 17:11 UTC, jcyamacho commented on versions.yaml
> +  - github.com/blacklane/go-libs/x/events/examples/without-auth
hi @IvanMartinezBL, thanks a lot for all ur feedback!!! 

In this case I can not see the diff, can u plz help me?

2022-05-30 06:56 UTC, shane-blacklane approved these changes
:rocket: :rocket: :rocket:

2022-05-30 06:56 UTC, shane-blacklane commented on Dockerfile
> +COPY . ./
newline needed :)

2022-05-30 06:56 UTC, shane-blacklane commented on Makefile
> +MISSPELL = $(TOOLS)/misspell
nice :+1:

2022-05-30 06:56 UTC, shane-blacklane commented on versions.yaml
> +  - github.com/blacklane/go-libs/x/events/examples/without-auth
it's just a newline at the end of file suggestion i think :)

2022-05-30 07:50 UTC, IvanMartinezBL commented on versions.yaml
> +  - github.com/blacklane/go-libs/x/events/examples/without-auth
Exactly. Github shows a red icon when the file doesn't end in newline. Just that.

2022-05-30 07:51 UTC, IvanMartinezBL approved these changes

2022-05-30 08:05 UTC, shane-blacklane approved these changes

2022-05-30 08:08 UTC, jcyamacho commented
status not updated but drone pipeline is ok: https://drone.blacklane.com/blacklane/go-libs/535

2022-05-30 08:09 UTC, merged

2022-05-30 10:29 UTC, marcelo-xavier-bl reviewed
Good job, thank you!

2022-05-30 10:29 UTC, marcelo-xavier-bl commented on otel/http.go
> +func InstrumentTransport(t http.RoundTripper) http.RoundTripper {
Nice one!