Remove event succeeded log from EventConsumerLogger
blacklane/go-libs pull request #207
Opened 2023-06-02 14:24 UTC by muzfr7

# CHANGES
Removing `log.Info().Msgf("%s succeeded", evName)` from `EventConsumerLogger()` middleware since it is generating an excessive number of logs on behalf of our services.

2023-06-02 14:26 UTC, sabaraouf approved these changes

2023-06-02 15:19 UTC, jcyamacho requested changes

2023-06-02 15:19 UTC, jcyamacho commented on logger/middleware/events.go
> -			log.Info().Msgf("%s succeeded", evName)
the only purpose of the `EventConsumerLogger` is to log, removing this line is invalidating the full middleware. Middlewares are optionals and can be configured in the services depending of our expectations, maybe the problem can be solved with a different strategy, if you are open to ideas we can talk about it

2023-06-02 15:31 UTC, muzfr7 commented on logger/middleware/events.go
> -			log.Info().Msgf("%s succeeded", evName)
thanks for the review @jcyamacho 🙏, as discussed [here](https://blacklane.slack.com/archives/C04N0S7D89L/p1685715273608529), I'll update this PR to create another middleware without that log..

2023-06-02 15:39 UTC, jcyamacho commented on logger/middleware/events.go
> -			log.Info().Msgf("%s succeeded", evName)
thanks @muzfr7, maybe we can do a smart duplication if for example we extract only what we need from this middleware to a new one, but instead of just duplicating we call the new one from it and thus keep the behavior intact.... just thinking.. 🤔 WDYT?

2023-06-06 05:18 UTC, muzfr7 commented on logger/middleware/events.go
> -			log.Info().Msgf("%s succeeded", evName)
That would be great ⚡️

2023-06-06 05:18 UTC, muzfr7 commented
Closing this PR since we dealt with the issue locally within our service!

2023-06-06 05:18 UTC, closed without merging