Wait for the server to start before making requests in probe tests
blacklane/go-libs pull request #89
Opened 2021-12-01 15:18 UTC by IvanMartinezBL

Current probe tests may fail because the server didn't start before requests are sent. This adds a `time.Sleep` before sending requests, which doesn't ensure the server is started but makes it way more probable.

2021-12-02 12:58 UTC, giulliano-bueno commented
@IvanMartinezBL thanks for your PR. Please check our README and follow our standard.
https://github.com/blacklane/go-libs#commit-messages-issues-and-pull-requests

2021-12-02 12:59 UTC, giulliano-bueno requested changes
Simple change, check our README and follow our commit message standard please.

2021-12-17 16:17 UTC, IvanMartinezBL commented
@giulliano-bueno I changed the commit message as requested

2022-01-13 10:17 UTC, giulliano-bueno approved these changes
LGTM.

2022-01-13 12:26 UTC, merged