[OS-2623] adding ctx
blacklane/go-libs pull request #90
Opened 2021-12-05 22:33 UTC by shruthiMaganahalli

2021-12-06 09:06 UTC, shane-blacklane commented
Code changes look good, but you need to follow the PR standards on this repo: https://github.com/blacklane/go-libs#commit-messages-issues-and-pull-requests

2021-12-06 11:25 UTC, stephde requested changes

2021-12-06 11:25 UTC, stephde commented on camunda/client.go
> +func (c *client) Subscribe(ctx context.Context, topicName string, workerID string, handler TaskHandler, options ...func(*Subscription)) *Subscription {
I'm not sure if it makes sense to pass a context to this function. This is only called once when the service starts and initializes the subscription. Therefore, any `TaskHandlerFunc` triggered from this function will receive the same context instance.
I'm not sure if this is a problem, but I feel like it makes more sense to have separate contexts for each handler call. So IMHO it makes more sense to generate a new context in the `fetch()` function. The events lib is handling this in the same way so I think we should stick to that
https://github.com/blacklane/go-libs/blob/master/x/events/consumer.go#L201
One main thing we want to achieve with the context is to pass the logger indirectly. So we would have to pass the logger instance here instead and manually inject that into the context. But I suppose the library should not really know about the logger. The events library solves this by introducing middlewares. I guess that would be the best way to solve this here as well. However thats a bit more effort. Let me know your thoughts on this 
🥔

2022-01-24 12:59 UTC, sabaraouf commented on camunda/client.go
> +func (c *client) Subscribe(ctx context.Context, topicName string, workerID string, handler TaskHandler, options ...func(*Subscription)) *Subscription {
i dont see the difference in the 2 PRs https://github.com/blacklane/go-libs/pull/97. also stephan's suggestion was to create a new context in `fetch()` but it doesn't look like so 🤔

2023-02-01 18:09 UTC, shane-blacklane commented
closing due to inactivity

2023-02-01 18:09 UTC, closed without merging